### ISSUE TITLE
AlexaPi not running and has error

### ISSUE THREAD

**Issue by dony71** [sammachin/AlexaPi#58]
AlexaPi is not running after installation and reboot
/var/log/alexapi.log shows below
---------------------------------------------------------------------------------------------------
Starting Alexa...
Checking Internet Connection
Connection OK
Traceback (most recent call last):
  File "/root/AlexaPi/main.py", line 150, in <module>
    token = gettoken()
  File "/root/AlexaPi/main.py", line 43, in gettoken
    refresh = refresh_token
NameError: global name 'refresh_token' is not defined

What am I missing?

**Comment by dony71** [comment]
fix by adding below in creds.py
refresh_token = ''
